---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.11.0'
        - name: Install pipenv
          run: pip install pipenv

        - name: Install dependencies
          run: pipenv install --dev

        - name: Print working directory
          run: pwd

        - name: List files
          run: ls -la

        - name: Test
          working-directory: ${{ github.workspace }}
          run: pipenv run python manage.py test

        - name: Lint
          working-directory: ${{ github.workspace }}
          run: pipenv run flake8