---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.0"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev
          pipenv install -r requirements.dev.txt

      - name: Print working directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Test
        working-directory: ${{ github.workspace }}
        run: pipenv run python manage.py test

      - name: Lint
        working-directory: ${{ github.workspace }}
        run: pipenv run flake8
